name: Validate with hassfest

on:
  push:
    paths-ignore:
    - pyproject.toml
  pull_request:
    paths-ignore:
    - pyproject.toml
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: home-assistant/actions/hassfest@master
