name: Ruff — Unused Imports Check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: pip install ruff

      - name: Ruff (report all issues, non-blocking)
        run: ruff check custom_components/ambient_music --output-format=github
        continue-on-error: true

      - name: Ruff (enforce no unused imports)
        run: ruff check custom_components/ambient_music --select F401 --output-format=github
